name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.1','7.2','7.3','7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:7.5.20
      - name: Run tests
        run: phpunit
